name: Cache

inputs:
  python-version:
    required: true
  poetry-version:
    required: true

runs:
  using: composite
  steps:
    - uses: actions/cache@v2.1.6
      id: load-poetry-cache
      with:
        path: $HOME/.local
        key: poetry-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.poetry-version }}

    - uses: actions/cache@v2.1.6
      id: load-env-cache
      with:
        path: $HOME/.cache/pypoetry
        key: virtualenv-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.poetry-version }}
