name: Setup Environment
description: Sets up python, poetry, virtualenvs, and caching

inputs:
  python-version:
    required: true
    description: Verison of python to use for cache key
  poetry-version:
    required: true
    description: Version of poetry to install (if cache miss)

runs:
  using: composite
  steps:
    - name: Setup python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Load poetry cache
      id: load-poetry-cache
      uses: actions/cache@v2.1.6
      with:
        path: $HOME/.local
        key: ${{ github.ref_name }}-poetry-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.poetry-version }}

    - name: Load virtualenv cache
      id: load-env-cache
      uses: actions/cache@v2.1.6
      with:
        path: $HOME/.cache/pypoetry
        key: ${{ github.head_ref }}-env-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.poetry-version }}

    - name: Update PATH to include poetry
      if: steps.load-caches.outputs.cache-hit == 'true'
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: Install poetry ${{ inputs.poetry-version }}
      if: steps.load-poetry-cache.outputs.cache-hit != 'true'
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ inputs.poetry-version }}

    - name: Set virutalenv
      run: poetry env use ${{ inputs.python-version }}
      shell: bash

    - name: Install dependencies
      if: steps.load-env-cache.outputs.cache-hit != 'true'
      run: poetry install
      shell: bash
