name: Pull Request
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
    runs-on: ubuntu-latest
    container: ghcr.io/paulhutchings/bearboto3:${{ matrix.python-version }}
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Lint code
        run: pylint bearboto3

  test:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
    runs-on: ubuntu-latest
    container: ghcr.io/paulhutchings/bearboto3:${{ matrix.python-version }}
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Run unit tests
        run: pytest
